import { Product } from "./types";

export const products: Product[] = [
  {
    id: 1,
    name: "Wireless Noise-Cancelling Headphones",
    price: 249.99,
    originalPrice: 329.99,
    rating: 4.8,
    reviewCount: 2341,
    category: "Electronics",
    image: "/images/wireless-noise-cancelling-headphones.jpg",
    badge: "Sale",
    description: "Premium sound with 30-hour battery life and active noise cancellation.",
  },
  {
    id: 2,
    name: "Minimalist Leather Watch",
    price: 189.00,
    rating: 4.6,
    reviewCount: 876,
    category: "Accessories",
    image: "/images/minimalist-leather-watch.jpg",
    description: "Slim profile with genuine leather strap and sapphire crystal glass.",
  },
  {
    id: 3,
    name: "Ultralight Running Sneakers",
    price: 129.95,
    originalPrice: 159.95,
    rating: 4.7,
    reviewCount: 1543,
    category: "Footwear",
    image: "/images/ultralight-running-sneakers.jpg",
    badge: "Sale",
    description: "Breathable mesh upper with responsive foam cushioning for all-day comfort.",
  },
  {
    id: 4,
    name: "Portable Bluetooth Speaker",
    price: 79.99,
    rating: 4.5,
    reviewCount: 3210,
    category: "Electronics",
    image: "/images/portable-bluetooth-speaker.jpg",
    description: "360° surround sound with 12-hour playtime and waterproof design.",
  },
  {
    id: 5,
    name: "Merino Wool Crewneck Sweater",
    price: 95.00,
    rating: 4.9,
    reviewCount: 412,
    category: "Clothing",
    image: "/images/merino-wool-crewneck-sweater.jpg",
    badge: "New",
    description: "Sustainably sourced merino wool, naturally temperature-regulating.",
  },
  {
    id: 6,
    name: "Stainless Steel Water Bottle",
    price: 34.99,
    rating: 4.7,
    reviewCount: 5678,
    category: "Accessories",
    image: "/images/stainless-steel-water-bottle.jpg",
    description: "Double-wall insulation keeps drinks cold 24h or hot 12h.",
  },
  {
    id: 7,
    name: "Smart Fitness Tracker Band",
    price: 59.99,
    originalPrice: 89.99,
    rating: 4.4,
    reviewCount: 2109,
    category: "Electronics",
    image: "/images/smart-fitness-tracker-band.jpg",
    badge: "Sale",
    description: "Track steps, heart rate, sleep, and receive smart notifications.",
  },
  {
    id: 8,
    name: "Canvas Tote Backpack",
    price: 68.00,
    rating: 4.6,
    reviewCount: 734,
    category: "Accessories",
    image: "/images/canvas-tote-backpack.jpg",
    description: "Durable waxed canvas with laptop sleeve and multiple pockets.",
  },
  {
    id: 9,
    name: "Slim Fit Chino Pants",
    price: 74.95,
    rating: 4.5,
    reviewCount: 988,
    category: "Clothing",
    image: "/images/slim-fit-chino-pants.jpg",
    description: "Stretch cotton blend for a tailored look with all-day comfort.",
  },
  {
    id: 10,
    name: "Leather Chelsea Boots",
    price: 219.00,
    originalPrice: 269.00,
    rating: 4.8,
    reviewCount: 561,
    category: "Footwear",
    image: "/images/leather-chelsea-boots.jpg",
    badge: "Sale",
    description: "Full-grain leather upper with elastic side panels and stacked heel.",
  },
  {
    id: 11,
    name: "Mechanical Keyboard TKL",
    price: 149.99,
    rating: 4.9,
    reviewCount: 1876,
    category: "Electronics",
    image: "/images/mechanical-keyboard-tkl.jpg",
    badge: "New",
    description: "Tenkeyless layout with tactile switches and RGB backlighting.",
  },
  {
    id: 12,
    name: "Linen Button-Down Shirt",
    price: 59.00,
    rating: 4.6,
    reviewCount: 643,
    category: "Clothing",
    image: "/images/linen-button-down-shirt.jpg",
    description: "Breathable linen fabric, perfect for warm weather and casual occasions.",
  },
];

export const categories = ["All", "Electronics", "Clothing", "Footwear", "Accessories"];
